insert into author(id, first_name, last_name) values(1, 'Debbie', 'Macomber');
insert into author(id, first_name, last_name) values(2, 'Megan', 'Miranda');
insert into author(id, first_name, last_name) values(3, 'Laura', 'Lippman');
insert into author(id, first_name, last_name) values(4, 'Nora', 'Roberts');
insert into author(id, first_name, last_name) values(5, 'Delia', 'Owens');
insert into author(id, first_name, last_name) values(6, 'Elizabeth', 'Gilbert');
insert into author(id, first_name, last_name) values(7, 'David', 'Baldacci');
insert into author(id, first_name, last_name) values(8, 'Mary Beth', 'Keane');
insert into author(id, first_name, last_name) values(9, 'Shari', 'Lapena');
insert into author(id, first_name, last_name) values(10, 'George', 'Orwell');
insert into author(id, first_name, last_name) values(11, 'Daniel', 'Silva');
insert into author(id, first_name, last_name) values(12, 'Pierce', 'Brown');
insert into author(id, first_name, last_name) values(13, 'Elin', 'Hilderbrand');
insert into author(id, first_name, last_name) values(14, 'Colson', 'Whitehead');
insert into author(id, first_name, last_name) values(15, 'Catherine', 'Coulter');
insert into author(id, first_name, last_name) values(16, 'Richard', 'Russo');
